/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.*;
import java.awt.event.*;
import database.Conexion;
import core.Kanji;
import javax.swing.WindowConstants;
import core.Score;
import java.awt.Font;
import java.io.*;
/**
 *
 * @author unzero
 */
public class select_lecture extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form select_lecture
     */
    public select_lecture(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bienvenido, por favor ingrese la lectura correcta para el kanji:");

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel2)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private Conexion conexion;
    private Random number_generator;
    private int ac;
    private Kanji in_study;
    private Score points;
    private Font fuente_label;
    private Font fuente_boton;
    public select_lecture(java.awt.Frame parent,boolean modal,Conexion conx,Score pnt){
        
        this(parent,modal);
        
        try{
             InputStream myStream = new BufferedInputStream(new FileInputStream("/home/unzero/font.ttc"));
             Font ttfBase = Font.createFont(Font.TRUETYPE_FONT, myStream); 
             fuente_label = ttfBase.deriveFont(Font.TRUETYPE_FONT, 80);
             fuente_boton = ttfBase.deriveFont(Font.TRUETYPE_FONT,20);
        
        }catch(Exception e){
            e.printStackTrace();
        }
        
        if(fuente_label != null){
            jLabel2.setFont(fuente_label);
            jButton1.setFont(fuente_boton);
            jButton2.setFont(fuente_boton);
            jButton3.setFont(fuente_boton);
            jButton4.setFont(fuente_boton);
        }
        
        conexion = conx;
        points = pnt;
        number_generator = new Random();
        this.setTitle("Elige la lectura");
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
        this.setLocationRelativeTo(parent);
        //jLabel2.setFont(new Font("Serif",Font.PLAIN,50));
        //quitar elementos de decoracion
       // this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        run();
        this.setVisible(true);
    }
    
    public void run(){
        in_study = conexion.get( number_generator.nextInt( conexion.size() ) );
        jLabel2.setText(in_study.get_kanji());
        int id = number_generator.nextInt( in_study.size() );
        ac = number_generator.nextInt( 4 );
        switch(ac){
            case 0:
                jButton1.setText( in_study.get_lecture( id ) );
                jButton2.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton3.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton4.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                break;
            case 1:
                jButton1.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton2.setText( in_study.get_lecture( id ) );
                jButton3.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton4.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                break;
            case 2:
                jButton1.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton2.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton3.setText( in_study.get_lecture( id ) );
                jButton4.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                break;
            case 3:
                jButton1.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton2.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton3.setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                jButton4.setText( in_study.get_lecture( id ) );
                break;
        }
    }

    @Override
    public void actionPerformed(ActionEvent ev){
        int pulsed = -1;
        if(ev.getSource() == jButton1){
            pulsed = 0;
        }else if(ev.getSource() == jButton2){
            pulsed = 1;
        }else if(ev.getSource() == jButton3){
            pulsed = 2;
        }else if(ev.getSource() == jButton4){
            pulsed = 3;
        }
        if(pulsed == ac){
            core.Common.message("お疲れさま!");
            points.plus();
        }else{
            core.Common.errorMessage("Las lecturas correctas eran: "+in_study.toString());
        }
        this.dispose();
    }
    
}
