/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.*;
import java.awt.event.*;
import database.Conexion;
import core.Kanji;
import core.Score;
import java.awt.Font;
import java.io.*;
import javax.swing.*;
import core.Fuente;
/**
 *
 * @author unzero
 */
public class select_lecture extends javax.swing.JDialog implements ActionListener{

    /**
     * Creates new form select_lecture
     */
    public select_lecture(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bienvenido, por favor ingrese la lectura correcta para el kanji:");

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel2)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private Conexion conexion;
    private Random number_generator;
    private int ac;
    private Kanji in_study;
    private Score points;
    private Font fuente_label;
    private Font fuente_boton;
    private JButton[] botones;
    
    public select_lecture(java.awt.Frame parent,boolean modal,Conexion conx,Score pnt){
        
        this(parent,modal);
        
        conexion = conx;
        points = pnt;
        number_generator = new Random();
        fuente_label = new Fuente(80).getFont();
        fuente_boton = new Fuente(20).getFont(); 
        
        if(fuente_label != null){
            jLabel2.setFont(fuente_label);
        }
        
        botones = new JButton[]{jButton1,jButton2,jButton3,jButton4};
        for(JButton el : botones){
            if(fuente_boton != null)el.setFont(fuente_boton);
            el.addActionListener(this);
        }
        
        //jLabel2.setFont(new Font("Serif",Font.PLAIN,50));
        //quitar elementos de decoracion
       // this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle("Elige la lectura");
        this.setLocationRelativeTo(parent);
        run();
        
        //creating the alarm, it sumulates the time that the user have to answer 
       /* Thread tt = new Thread( new Alarm(botones[(ac+1)%4]));
        tt.start();
        */
        this.setVisible(true);
        System.out.println("OK");
        /*try{
            if(tt.getState() == Thread.State.TIMED_WAITING){
                tt.notify();
            }
            tt.join();
        }catch(Exception ex){}*/
    }
    
    public void run(){
        in_study = conexion.get( number_generator.nextInt( conexion.size() ) );
        jLabel2.setText(in_study.get_kanji());
        ac = number_generator.nextInt( 4 );
        for(int x=0;x<4;++x){
            if( ac == x ){
                botones[x].setText( in_study.get_lecture( number_generator.nextInt( in_study.size() ) ) );
            }else{
                do{
                    botones[x].setText( conexion.get_lecture( number_generator.nextInt( conexion.total_lectures() ) ) );
                }while( in_study.get_lectures().indexOf(  botones[x].getText() ) != -1 );
            }
        }
        
    }

    @Override
    public void actionPerformed(ActionEvent ev){
        if(!this.isFocused())return;
        boolean flag = false;
        if( ev.getSource() instanceof JButton){
            if( in_study.get_lectures().indexOf(  ((JButton)ev.getSource()).getText() ) != -1 ){
                flag = true;
            }
        }
        if(flag){
            core.Common.message("お疲れさま!");
            points.plus();
        }else{
            core.Common.errorMessage("Las lecturas correctas eran: "+in_study.toString());
        }
        this.dispose();
    }
    
}

class Alarm implements Runnable{
    private JButton toActive;
    
    public  Alarm(JButton toActive){
        this.toActive = toActive;
    }
    
    public void run(){
        try{
            Thread.sleep(4000);
        }catch(Exception ex){
            
        }
        toActive.doClick();
    }
}